
## Practices from the HackerRank SQL Tutorial
## https://www.hackerrank.com/domains/sql
USE world;
SELECT *
FROM CITY
WHERE COUNTRYCODE = 'USA'
AND POPULATION > 100000;
SELECT *
FROM CITY;
SELECT *
FROM CITY
WHERE ID = '1661';

SELECT *
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT NAME, POPULATION
FROM CITY
WHERE COUNTRYCODE = 'USA';

SELECT NAME, POPULATION
FROM CITY
WHERE COUNTRYCODE = 'JPN'
AND POPULATION > 900000;

SELECT COUNTRYCODE, LANGUAGE, ISOFFICIAL, PERCENTAGE
FROM COUNTRYLANGUAGE
WHERE ISOFFICIAL = 'T';

SELECT COUNTRYCODE, LANGUAGE, PERCENTAGE
FROM COUNTRYLANGUAGE
WHERE PERCENTAGE > 50;

SELECT LANGUAGE, COUNT(*)
FROM COUNTRYLANGUAGE
GROUP BY LANGUAGE
HAVING COUNT(*) > 1;

SELECT COUNTRYCODE, LANGUAGE
FROM COUNTRYLANGUAGE
WHERE LANGUAGE = 'English';

SELECT COUNTRYCODE, LANGUAGE, PERCENTAGE
FROM COUNTRYLANGUAGE
WHERE COUNTRYCODE = 'USA';